using Content.Shared._NC.RTS.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NC.RTS.UI;

[GenerateTypedNameReferences]
public sealed partial class RTSControlWindow : DefaultWindow
{
    public event Action<RTSCommandType>? OnCommandIssued;
    public event Action? OnStopIssued;

    public RTSControlWindow()
    {
        RobustXamlLoader.Load(this);

        MoveButton.OnPressed += _ => OnCommandIssued?.Invoke(RTSCommandType.Move);
        AttackMoveButton.OnPressed += _ => OnCommandIssued?.Invoke(RTSCommandType.AttackMove);
        AttackTargetButton.OnPressed += _ => OnCommandIssued?.Invoke(RTSCommandType.AttackTarget);
        HoldButton.OnPressed += _ => OnCommandIssued?.Invoke(RTSCommandType.HoldPosition);
        StopButton.OnPressed += _ => OnStopIssued?.Invoke();
    }

    public void UpdateSelectionCount(int count)
    {
        SelectionCountLabel.Text = $"Units Selected: {count}";
    }
}
