using Content.Client.UserInterface.Controls;
using Content.Shared._Mriya.BureaucraticComputer;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Text.RegularExpressions;

namespace Content.Client._Mriya.BureaucraticComputer.UI;

[GenerateTypedNameReferences]
public sealed partial class BureaucracyComputerWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private ILocalizationManager _loc = default!;

    public readonly Dictionary<string, TextEdit> InputControls = new();

    public Action<BureaucraticDocumentPrototype>? OnDocumentSelected;
    public Action<string, Dictionary<string, string>>? OnPrintPressed;

    private ProtoId<BureaucraticDocumentPrototype>? _selectedDocumentId;
    private BureaucracyAutoFillState? _autoFillData;

    public Regex FieldRegex = SharedBureacraticComputerSystem.FieldRegex;

    public BureaucracyComputerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var panelBg = new StyleBoxFlat { BackgroundColor = Color.FromHex("#1B1B1B") };
        LeftBackgroundPanel.PanelOverride = panelBg;
        RightBackgroundPanel.PanelOverride = panelBg;

        PopulateDocuments();

        PrintButton.OnPressed += _ =>
        {
            if (_selectedDocumentId == null)
                return;

            var filledData = new Dictionary<string, string>();
            foreach (var (key, textEdit) in InputControls)
            {
                filledData[key] = Rope.Collapse(textEdit.TextRope) ?? string.Empty;
            }

            OnPrintPressed?.Invoke(_selectedDocumentId, filledData);
        };
    }

    private void PopulateDocuments()
    {
        foreach (var document in _prototypeManager.EnumeratePrototypes<BureaucraticDocumentPrototype>())
        {
            var button = new Button
            {
                Text = document.Name
            };

            button.OnPressed += _ =>
            {
                OnDocumentSelected?.Invoke(document);
                GenerateFields(document);
            };

            DocumentList.AddChild(button);
        }
    }

    private void GenerateFields(BureaucraticDocumentPrototype document)
    {
        DocumentFields.RemoveAllChildren();
        InputControls.Clear();

        _selectedDocumentId = document.ID;
        PrintButton.Disabled = false;

        var documentTitle = new Label
        {
            Text = document.Name,
            HorizontalAlignment = HAlignment.Center,
            FontColorOverride = Color.FromHex("#5E9CFF"),
            Margin = new Thickness(0, 0, 0, 20)
        };
        documentTitle.StyleClasses.Add("LabelHeading");
        DocumentFields.AddChild(documentTitle);

        var matches = FieldRegex.Matches(document.Text);
        var processedFields = new HashSet<string>();

        foreach (Match match in matches)
        {
            var fieldId = match.Groups[1].Value.Trim();
            var headerText = match.Groups[2].Success ? match.Groups[2].Value.Trim() : fieldId;

            if (!processedFields.Add(fieldId))
                continue;

            var finalHeader = _loc.TryGetString(headerText, out var locStr) ? locStr : headerText;

            var container = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(0, 0, 0, 10)
            };

            var label = new Label
            {
                Text = $"▶ {finalHeader.ToUpper()}:",
                FontColorOverride = Color.FromHex("#EAEAEA"),
                Margin = new Thickness(0, 0, 0, 4)
            };
            label.StyleClasses.Add("LabelKeyText");

            var textEditBackground = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#2C2C34") },
                HorizontalExpand = true
            };

            var textEdit = new TextEdit
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                MinHeight = 40,
                Margin = new Thickness(5)
            };

            textEdit.ToolTip = _loc.GetString("bureaucratic-computer-window-text-edit-tooltip");

            var prefilledText = string.Empty;
            switch (fieldId.ToLowerInvariant())
            {
                case "stationname":
                    prefilledText = _autoFillData?.StationName ?? "";
                    break;
                case "username":
                    prefilledText = _autoFillData?.CharacterName ?? "";
                    break;
                case "userjob":
                    prefilledText = _autoFillData?.CharacterJob ?? "";
                    break;
                case "date":
                    prefilledText = DateTime.Now.AddYears(210).ToString("dd.MM.yyyy");
                    break;
            }

            if (!string.IsNullOrEmpty(prefilledText))
            {
                textEdit.TextRope = new Rope.Leaf(prefilledText);
            }

            textEdit.OnTextChanged += args =>
            {
                var text = Rope.Collapse(args.Control.TextRope) ?? string.Empty;
                var lineCount = text.Split('\n').Length;
                args.Control.MinHeight = Math.Max(40, lineCount * 30 + 10);

                UpdatePreview();
            };

            textEditBackground.AddChild(textEdit);
            container.AddChild(label);
            container.AddChild(textEditBackground);

            DocumentFields.AddChild(container);
            InputControls.Add(fieldId, textEdit);
        }

        UpdatePreview();
    }

    private void UpdatePreview()
    {
        if (_selectedDocumentId == null || PreviewTextLabel == null)
            return;

        if (!_prototypeManager.TryIndex<BureaucraticDocumentPrototype>(_selectedDocumentId, out var doc))
            return;

        var previewText = doc.Text;

        foreach (Match match in FieldRegex.Matches(doc.Text))
        {
            var fullMatch = match.Value; // Наприклад: [stationname|Назва]
            var fieldId = match.Groups[1].Value.Trim();

            // Беремо текст з TextEdit, якщо він є, інакше ставимо лінію для краси
            var replacement = InputControls.TryGetValue(fieldId, out var input)
                ? (Rope.Collapse(input.TextRope) ?? string.Empty)
                : string.Empty;

            if (string.IsNullOrWhiteSpace(replacement))
            {
                replacement = "_________";
            }

            previewText = previewText.Replace(fullMatch, replacement);
        }
        var coloredPreview = $"[color=#000]{previewText}[/color]";

        var msg = new FormattedMessage();
        msg.AddMarkupPermissive(coloredPreview);
        PreviewTextLabel.SetMessage(msg);
    }

    public void UpdateAutoFill(BureaucracyAutoFillState state)
    {
        _autoFillData = state;
    }
}
